-- RLS를 일시적으로 비활성화
-- 개발 중에만 사용하고, 프로덕션에서는 반드시 RLS를 활성화해야 합니다!

-- 모든 테이블의 RLS 비활성화
ALTER TABLE schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE missions DISABLE ROW LEVEL SECURITY;
ALTER TABLE mission_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE earned_badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_qr_codes DISABLE ROW LEVEL SECURITY;

-- 또는 특정 테이블만 비활성화하려면:
-- ALTER TABLE users DISABLE ROW LEVEL SECURITY; 